# Use a small Python base image
FROM python:3.11-slim

# Set working directory
WORKDIR /app

# Copy requirements.txt and install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the project
COPY . .

# Default command to run Celery worker
CMD ["celery", "-A", "hello_django", "worker", "--loglevel=info"]
